### ISSUE TITLE
Intake Louis product for DevOps

### ISSUE THREAD

**Issue by rngadam** [ai-cfia/louis-legacy#1]
* [ ] versioned source and artefacts
* [x] an internal product documentation exist
* [x] a Project to manage this product has been created
  * https://github.com/orgs/ai-cfia/projects/2
 * [x] documented architecture with diagram
 * [ ] test plan
 * [ ] developer documentation
 * [ ] a continuous lint, test, build and deployment pipeline
   * [ ] an automated unit test suite
   * [ ] code is linted to standard
   * [ ] code builds to container
   * [ ] code deploys to cloud with publically available url
 * [ ] monitoring and reporting in place
   * [ ] of daily active users

**Comment by SonOfLope** [comment]
won't do. Archived
